name = "Tokelau"
author = "seherv"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c31f6ab992f13ab03dad5d0f917fc30ca3e9581628120890ba2a9dbb17fb424"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
